In [2]:
import numpy as np
print(type([1, 2, 3]))
print(type((1, 2, 3)))
print(type(np.array([1, 2, 3])))
print(type(np.array((1, 2, 3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.zeros(5) #1 solo número para el arreglo

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros([5,5]) #1 lista o tupla para una matriz de n dimensiones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros([1,2,3,2,1,3])

array([[[[[[0., 0., 0.]],

          [[0., 0., 0.]]],


         [[[0., 0., 0.]],

          [[0., 0., 0.]]],


         [[[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]]],


         [[[0., 0., 0.]],

          [[0., 0., 0.]]],


         [[[0., 0., 0.]],

          [[0., 0., 0.]]]]]])

In [7]:
np.zeros((1000,200))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [10]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [12]:
np.eye(10) #Matriz identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [16]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.arange(0,2,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [18]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [21]:
len(np.zeros(12))

12

In [22]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [24]:
arreglo = np.ones(9).reshape(3,3)

In [25]:
len(arreglo[0])

3

In [26]:
len(arreglo)

3

In [27]:
arreglo.shape

(3, 3)

In [28]:
np.arange(12).reshape(4,3)[1,1]

4

In [29]:
np.arange(12).reshape(4,3)[1][1]

4

In [30]:
a = np.array([10, 10, 10])

In [31]:
b = np.array([5, 5, 5])

In [32]:
a + b #Suma

array([15, 15, 15])

In [33]:
a - b #Resta

array([5, 5, 5])

In [34]:
#suma por un entero
a + 7

array([17, 17, 17])

In [35]:
a * b #Multiplicación

array([50, 50, 50])

In [36]:
a / b #Division

array([2., 2., 2.])

In [37]:
a % b

array([0, 0, 0], dtype=int32)

In [38]:
muestra = np.arange(20).reshape(5, 2, 2)
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [39]:
respuesta_glucosa = muestra > 5
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [40]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
respuesta_glucosa = (muestra % 2 == 0) & (muestra > 5) & (muestra < 14)
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])

In [3]:
A = np.arange(4).reshape((2, 2))
A

array([[0, 1],
       [2, 3]])

In [4]:
B = np.arange(4, 8).reshape((2, 2))
B

array([[4, 5],
       [6, 7]])

In [5]:
B.dot(A) #Producto punto entre matrices

array([[10, 19],
       [14, 27]])

In [6]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [7]:
np.dot(A, B)

array([[ 6,  7],
       [26, 31]])

In [13]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arreglo_doce.sum()

66

In [10]:
arreglo_doce.min()

0

In [11]:
arreglo_doce.max()

11

In [14]:
arreglo_doce.reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
arreglo_doce.sum()

66

In [16]:
arreglo_doce.reshape(3, 2, 2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [17]:
arreglo_doce.reshape(3, 2, 2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [18]:
arreglo_doce.reshape(3, 2, 2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])