In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array((0, 30, 45, 60, 90))
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [9]:
numero_random = np.random.randint(11)
numero_random

5

In [25]:
numero_random_negativo = np.random.randint(-9, 2)
numero_random_negativo

-9

In [27]:
arreglo_random = np.random.randint(10, 20, 8)
arreglo_random

array([19, 14, 12, 17, 12, 17, 18, 14])

In [28]:
np.random.rand(9)

array([0.84401146, 0.66737167, 0.52728065, 0.37474212, 0.83108431,
       0.71186437, 0.05529977, 0.25883609, 0.3515722 ])

In [29]:
np.random.rand(3, 2)

array([[0.2651009 , 0.07137584],
       [0.03163387, 0.33331358],
       [0.35803438, 0.38108977]])

In [30]:
np.average(arreglo_random)

15.375

In [31]:
np.median(arreglo_random)

15.5

In [32]:
np.mean(arreglo_random)

15.375

In [33]:
np.std(arreglo_random)

2.54644359843292

In [34]:
np.var(arreglo_random)

6.484375

In [35]:
arreglo_random.mean()

15.375